# deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: e2e
spec:
  replicas: 2
  selector:
    matchLabels:
      app: e2e
  template:
    metadata:
      labels:
        app: e2e
    spec:
      containers:
      - name: e2e
        image: oliver0313/e2e:latest
        ports:
        - containerPort: 8080

